# Generated by Django 2.0.7 on 2018-08-02 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180802_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='_parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Topic'),
        ),
    ]
