# Generated by Django 2.0.7 on 2018-08-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20180802_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_answer', models.TextField()),
                ('_time', models.DateTimeField(auto_now_add=True)),
                ('_best', models.BooleanField(default=False)),
                ('_author', models.ForeignKey(on_delete=None, to='forum.User')),
                ('_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Question')),
            ],
            options={
                'db_table': 'Answers',
            },
        ),
    ]
